name: push
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Lint and format code
        run: |
          npm run lint
          npm run format

      - name: Deploy
        run: npm run deploy
